Application\AdminBundle\Entity\Library:
    type: entity
    table: afes_library
    repositoryClass: Application\AdminBundle\Entity\Repository\LibraryRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
    lifecycleCallbacks: {  }
