Application\AdminBundle\Entity\Product:
    type: entity
    table: null
    repositoryClass: Application\AdminBundle\Entity\Repository\ProductRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        picture:
            type: string
            length: 255
        color:
            type: string
            length: 255
        stock:
            type: integer
    lifecycleCallbacks: {  }
