# AdminGenerator Configuration
admingenerator_generator:
    use_propel:           false
    use_doctrine_orm:     true
    use_doctrine_odm:     false
    base_admin_template: ApplicationAdminBundle::layout.html.twig
    dashboard_welcome_path: ApplicationAdminBundle_dashboard
    twig:
        use_form_resources: false
